#!/usr/bin/env bash
# Displays information about subdomains.

# Get specific domain info function
get_domain_info() {
    subdomain=$1
    dig_output=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:')

    if [ -z "$dig_output" ]; then
	    echo "Error: Unable to retrieve DNS information for $subdomain"
    else
	    record_type=$(echo "$dig_output" | awk '/IN\s/{print $4}')
	    destination=$(echo "$dig_output" | head -n1)
	    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main
domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then

    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        get_domain_info "$sub"
    done
else
    get_domain_info "$subdomain"
fi
