#!/usr/bin/env bash
# Install Nginx on a ubuntu webserver

# Updates package with superUser priviledges
# & installs Nginx on Ubuntu
echo -e "Installing Nginx for you! ;-)\n"
sudo apt-get update -y
sudo apt-get install -y nginx

# Starts Nginx &
# Configure Nginx to listen on port 80
sudo service nginx start

sudo bash -c 'echo "server {
    listen	80 default_server;
    listen	[::]:80 default_server;

    root	/var/www/html;
    index	index.html index.htm;

    server_name _;

    location / {
        return 200 \"Hello World!\\n\";
	default_type text/html;
    }
    
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
            try_files \$uri \$uri/ =404;
    }

    error_page 404 /404_custom_page.html;
    location = /404_custom_page.html {
        root /var/www/html;
	internal;
    }
}" > /etc/nginx/sites-available/default'

echo "Ceci n'est pas une page\n" > /var/www/html/404_custom_page.html

# Restart Nginx
sudo service nginx restart
