#!/usr/bin/env bash
# Install Nginx on ubuntu webservers

# Updates package with superUser priviledges
# & installs Nginx on Ubuntu
echo -e "Installing Nginx for you! ;-)\n"
sudo apt-get update -y
sudo apt-get install -y nginx

# Starts Nginx &
# Configure Nginx to listen on port 80
sudo service nginx start

sudo bash -c 'echo "server {
    listen	80 default_server;
    listen	[::]:80 default_server;

    root	/var/www/html;
    index	index.html index.htm;

    server_name _;

    location / {
        add_header Content-Type text/html;
	add_header X-Served-By $HOSTNAME;
        return 200 \"Hello World!\\n\";
    }

}" > /etc/nginx/sites-available/default'

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string404="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string404/" /etc/nginx/sites-available/default

string301="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string301/" /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
