#!/usr/bin/env bash
# Backup and compress my databases

date=$(date +"%d-%m-%Y")

file_name="$date.tar.gz"

mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file_name" backup.sql
