#!/usr/bin/env bash
# Configure ufw to block all incoming traffic
# except for TCP ports:
# 22 for SSH
# 443 for HTTPS SSL
# 80 for HTTP

sudo apt-get -y update
sudo apt-get -y install ufw

# Incoming & Outcoming permissions
sudo ufw disable
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Port permissions
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
