#!/usr/bin/env bash
# displays all active IPv4 IPs on a machine

ifconfig_output=$(ifconfig)

ipv4_addresses=$(echo "$ifconfig_output" | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | awk '{print $2}')

echo "$ipv4_addresses"
